# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default=b'description default'),
        ),
    ]
