# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20160909_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default=b'my location', max_length=6),
        ),
    ]
