# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20160909_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
