# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20160909_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default=b'my location', max_length=1200),
        ),
    ]
